#!/bin/zsh

log_info() {
  echo "$(date +%H:%M:%S) - $1"
}

reload_profile() {
  # shellcheck disable=SC1090
  source "$HOME/.zshrc"
}

log_info "Running laptop script."

(
  cd dotfiles || exit

  for dotfile in *
  do
    ln -nsf "${PWD}/${dotfile}" "${HOME}/.${dotfile}"
  done
)

if command -v brew >/dev/null 2>&1; then
  log_info "Updating Homebrew..."
  brew update
else
  log_info "Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

reload_profile

log_info "Running Brew bundler..."
brew bundle --no-upgrade
brew bundle --file=Caskfile

reload_profile

log_info "Setting macOS defaults."
./macos

reload_profile

terminal_theme=$(defaults read ~/Library/Preferences/com.apple.Terminal.plist "Default Window Settings" 2>/dev/null)
if [ "$terminal_theme" != "Ocean Dark" ]; then
  log_info "Install my Terminal theme."
  log_info "Location: laptop/themes/Ocean Dark.terminal"
fi

log_info "Done"
